import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ru: {
    // Header
    'header.contact.email': 'info@edestory.com',
    'header.contact.phone': '+7 (495) 123-45-67',
    'header.follow': 'Подписывайтесь:',
    'header.academy': 'СПОРТИВНАЯ АКАДЕМИЯ',
    'header.nav.home': 'ГЛАВНАЯ',
    'header.nav.programs': 'ПРОГРАММЫ',
    'header.nav.coaches': 'ТРЕНЕРЫ',
    'header.nav.schedule': 'РАСПИСАНИЕ',
    'header.nav.shop': 'МАГАЗИН',
    'header.nav.gallery': 'ГАЛЕРЕЯ',
    'header.nav.contact': 'КОНТАКТЫ',
    'header.cta': 'Пробная тренировка',
    'header.mobile.cta': 'Начать бесплатную тренировку',

    // Dropdown menus
    'dropdown.programs.boxing': 'Тренировки по боксу',
    'dropdown.programs.wrestling': 'Занятия борьбой',
    'dropdown.programs.kids': 'Детские программы (6-12)',
    'dropdown.programs.teens': 'Подростковые программы (13-17)',
    'dropdown.programs.adults': 'Взрослые программы (18+)',
    'dropdown.coaches.team': 'Наша команда',
    'dropdown.coaches.head': 'Главный тренер',
    'dropdown.coaches.trainers': 'Специализированные тренеры',
    'dropdown.schedule.timetable': 'Расписание занятий',
    'dropdown.schedule.personal': 'Персональные тренировки',
    'dropdown.schedule.groups': 'Групповые занятия',
    'dropdown.shop.boxing': 'Боксерское снаряжение',
    'dropdown.shop.wrestling': 'Борцовское снаряжение',
    'dropdown.shop.apparel': 'Одежда EDESTORY',
    'dropdown.shop.accessories': 'Тренировочные аксессуары',
    'dropdown.shop.nutrition': 'Питание и добавки',

    // Hero
    'hero.title1': 'СОЗДАЙ ДУХ',
    'hero.title2': 'ВОИНА',
    'hero.subtitle': 'Профессиональные тренировки по боксу и борьбе для чемпионов',
    'hero.description': 'Присоединяйся к EDESTORY Sports Academy и освой искусство боевых видов спорта с тренерами мирового класса',
    'hero.cta1': 'Начать тренировки',
    'hero.cta2': 'Смотреть видео',
    'hero.slide2.title': 'МАСТЕРСТВО БОКСА',
    'hero.slide2.subtitle': 'Освой благородное искусство',
    'hero.slide2.description': 'Развивай точность, силу и технику с нашей чемпионской программой бокса',
    'hero.slide2.cta1': 'Записаться на бокс',
    'hero.slide3.title': 'СИЛА БОРЬБЫ',
    'hero.slide3.subtitle': 'Освободи силу захватов',
    'hero.slide3.description': 'Развивай силу, выносливость и тактические навыки с нашей элитной программой борьбы',
    'hero.slide3.cta1': 'Начать борьбу',
    'hero.stats.students': 'Студентов обучено',
    'hero.stats.champions': 'Профессиональных чемпионов',
    'hero.stats.years': 'Лет совершенства',
    'hero.stats.medalists': 'Олимпийских медалистов в штате',
    'hero.cards.trainers.title': 'Опытные тренеры',
    'hero.cards.trainers.desc': 'Тренеры мирового класса с чемпионским опытом',
    'hero.cards.facilities.title': 'Современные залы',
    'hero.cards.facilities.desc': 'Профессиональный ринг, маты и оборудование',
    'hero.cards.schedule.title': 'Гибкое расписание',
    'hero.cards.schedule.desc': 'Утренние, дневные и вечерние занятия',
    'hero.cards.results.title': 'Проверенные результаты',
    'hero.cards.results.desc': '95% студентов достигают своих целей',

    // About
    'about.title': 'О EDESTORY Sports Academy',
    'about.subtitle': 'Создаем чемпионов через дисциплину и преданность',
    'about.hero.title': 'Где рождаются воины',
    'about.description': 'EDESTORY Sports Academy является ведущим центром тренировок по боевым видам спорта с 2016 года. Наш мировой класс объединяет традиционную мудрость боевых искусств с современными методами тренировок.',
    'about.points.coaching': 'Экспертные тренировки',
    'about.points.coaching.desc': 'Опыт международных чемпионатов',
    'about.points.results': 'Проверенные результаты',
    'about.points.results.desc': '85% успешности в соревнованиях',
    'about.points.focus': 'Индивидуальный подход',
    'about.points.focus.desc': 'Персонализированные программы тренировок',
    'about.points.development': 'Полное развитие',
    'about.points.development.desc': 'Физический, ментальный и технический рост',
    'about.cta': 'Узнать нашу историю',

    // Programs
    'programs.title': 'Программы тренировок',
    'programs.subtitle': 'Выбери свой путь к мастерству',
    'programs.boxing.title': 'ОСНОВЫ БОКСА',
    'programs.boxing.age': 'Возраст 8-16',
    'programs.boxing.desc': 'Освой благородное искусство с правильной техникой, работой ног и физической подготовкой',
    'programs.boxing.price': 'От 8,000₽/месяц',
    'programs.boxing.features.1': 'Базовые техники ударов',
    'programs.boxing.features.2': 'Тренировка работы ног',
    'programs.boxing.features.3': 'Физическая подготовка',
    'programs.boxing.cta': 'Записаться на бокс',
    'programs.wrestling.title': 'МАСТЕРСТВО БОРЬБЫ',
    'programs.wrestling.age': 'Возраст 10-18',
    'programs.wrestling.desc': 'Развивай превосходные навыки захватов, бросков и контроля на земле',
    'programs.wrestling.price': 'От 9,000₽/месяц',
    'programs.wrestling.features.1': 'Техники бросков',
    'programs.wrestling.features.2': 'Контроль на земле',
    'programs.wrestling.features.3': 'Подготовка к соревнованиям',
    'programs.wrestling.cta': 'Начать борьбу',
    'programs.kids.title': 'ДЕТСКИЕ ЕДИНОБОРСТВА',
    'programs.kids.age': 'Возраст 6-12',
    'programs.kids.desc': 'Безопасное знакомство с боевыми искусствами с акцентом на дисциплину и веселье',
    'programs.kids.price': 'От 6,500₽/месяц',
    'programs.kids.features.1': 'Техники соответствующие возрасту',
    'programs.kids.features.2': 'Развитие характера',
    'programs.kids.features.3': 'Навыки против буллинга',
    'programs.kids.cta': 'Детские занятия',
    'programs.adult.title': 'ФИТНЕС-БОКС ДЛЯ ВЗРОСЛЫХ',
    'programs.adult.age': 'Возраст 18+',
    'programs.adult.desc': 'Высокоинтенсивные боксерские тренировки для фитнеса и снятия стресса',
    'programs.adult.price': 'От 7,500₽/месяц',
    'programs.adult.features.1': 'Кардио подготовка',
    'programs.adult.features.2': 'Тренировка техники',
    'programs.adult.features.3': 'Управление стрессом',
    'programs.adult.cta': 'Взрослые тренировки',
    'programs.competition.title': 'ПОДГОТОВКА К СОРЕВНОВАНИЯМ',
    'programs.competition.age': 'Только продвинутые',
    'programs.competition.desc': 'Элитные тренировки для спортсменов и подготовка к турнирам',
    'programs.competition.price': 'От 15,000₽/месяц',
    'programs.competition.features.1': 'Индивидуальные тренировки',
    'programs.competition.features.2': 'Соревновательная стратегия',
    'programs.competition.features.3': 'Ментальная подготовка',
    'programs.competition.cta': 'Стать профи',
    'programs.personal.title': 'ПЕРСОНАЛЬНЫЕ ТРЕНИРОВКИ',
    'programs.personal.age': 'Все возраста',
    'programs.personal.desc': 'Индивидуальные занятия, адаптированные под ваши конкретные цели и потребности',
    'programs.personal.price': 'От 3,500₽/занятие',
    'programs.personal.features.1': 'Индивидуальные программы',
    'programs.personal.features.2': 'Гибкое расписание',
    'programs.personal.features.3': 'Быстрый прогресс',
    'programs.personal.cta': 'Забронировать',
    'programs.bottom.text': 'Не знаете, какая программа вам подходит?',
    'programs.bottom.cta': 'Запланировать бесплатную консультацию',

    // Why Choose Us
    'why.title': 'Почему выбирают EDESTORY?',
    'why.subtitle': 'Что делает нас особенными',
    'why.coaches.title': 'ТРЕНЕРЫ МИРОВОГО КЛАССА',
    'why.coaches.stat': '15+ лет среднего опыта',
    'why.coaches.desc': 'Наши тренеры - бывшие профессиональные спортсмены и сертифицированные тренеры с опытом международных соревнований.',
    'why.facilities.title': 'СОВРЕМЕННЫЕ ЗАЛЫ',
    'why.facilities.stat': '2,500 м² тренировочного пространства',
    'why.facilities.desc': 'Профессиональный боксерский ринг, борцовские маты, современное оборудование и специальные зоны для разных видов тренировок.',
    'why.methodology.title': 'ПРОВЕРЕННАЯ МЕТОДИКА',
    'why.methodology.stat': '95% достижения целей',
    'why.methodology.desc': 'Наши структурированные программы тренировок сочетают традиционные техники с современной спортивной наукой для оптимальных результатов.',
    'why.flexibility.title': 'ГИБКИЕ ПРОГРАММЫ',
    'why.flexibility.stat': 'Расписание 6 дней в неделю',
    'why.flexibility.desc': 'Утренние, дневные и вечерние занятия под ваш образ жизни. Доступны мастер-классы выходного дня и специальные мероприятия.',

    // Features
    'features.title': 'Что вы получите',
    'features.subtitle': 'Полный опыт тренировок',
    'features.step1.title': 'ОЦЕНКА И ПОСТАНОВКА ЦЕЛЕЙ',
    'features.step1.desc': 'Персональная оценка и разработка индивидуального плана тренировок',
    'features.step1.time': 'Неделя 1',
    'features.step2.title': 'ОСНОВНЫЕ ТЕХНИКИ',
    'features.step2.desc': 'Освоение базовых ударов, работы ног и защитных движений',
    'features.step2.time': 'Недели 2-8',
    'features.step3.title': 'РАЗВИТИЕ НАВЫКОВ',
    'features.step3.desc': 'Продвинутые комбинации, подготовка к спаррингу и физическая подготовка',
    'features.step3.time': 'Недели 9-16',
    'features.step4.title': 'ГОТОВНОСТЬ К СОРЕВНОВАНИЯМ',
    'features.step4.desc': 'Подготовка к турнирам, продвинутая стратегия и пиковая производительность',
    'features.step4.time': 'Неделя 16+',
    'features.metrics.title': 'Метрики успеха тренировок',
    'features.metrics.subtitle': 'Реальные результаты от нашего структурированного подхода',
    'features.metrics.achievement': 'Достижение целей',
    'features.metrics.progress': 'Недель до прогресса',
    'features.metrics.competition': 'Готовность к соревнованиям',
    'features.metrics.satisfaction': 'Уровень удовлетворенности',

    // Pricing
    'pricing.title': 'Планы членства',
    'pricing.subtitle': 'Гибкие варианты для каждой цели',
    'pricing.save': 'Сэкономьте 15% с годовым членством',
    'pricing.starter.name': 'СТАРТЕР',
    'pricing.starter.desc': 'Идеально для начинающих',
    'pricing.starter.feature1': '2 занятия в неделю',
    'pricing.starter.feature2': 'Базовое оборудование включено',
    'pricing.starter.feature3': 'Доступ к раздевалке',
    'pricing.starter.feature4': 'Программы для начинающих',
    'pricing.starter.feature5': 'Только групповые тренировки',
    'pricing.starter.cta': 'Выбрать Стартер',
    'pricing.champion.name': 'ЧЕМПИОН',
    'pricing.champion.desc': 'Самый популярный выбор',
    'pricing.champion.badge': 'ЛУЧШЕЕ ПРЕДЛОЖЕНИЕ',
    'pricing.champion.feature1': 'Безлимитные групповые занятия',
    'pricing.champion.feature2': '2 персональные тренировки',
    'pricing.champion.feature3': 'Подготовка к соревнованиям',
    'pricing.champion.feature4': 'Консультация по питанию',
    'pricing.champion.feature5': 'Доступ ко всему оборудованию',
    'pricing.champion.feature6': 'Приоритетное бронирование',
    'pricing.champion.cta': 'Выбрать Чемпион',
    'pricing.elite.name': 'ЭЛИТ',
    'pricing.elite.desc': 'Для серьезных спортсменов',
    'pricing.elite.feature1': 'Безлимитный полный доступ',
    'pricing.elite.feature2': '4 персональные тренировки',
    'pricing.elite.feature3': 'Соревновательное наставничество',
    'pricing.elite.feature4': 'Индивидуальные планы питания',
    'pricing.elite.feature5': 'Восстановительные процедуры',
    'pricing.elite.feature6': 'Гостевые привилегии',
    'pricing.elite.cta': 'Выбрать Элит',
    'pricing.additional.title': 'Дополнительные услуги',
    'pricing.additional.personal': 'Персональная тренировка',
    'pricing.additional.competition': 'Подготовка к соревнованиям',
    'pricing.additional.nutrition': 'Консультация по питанию',
    'pricing.bottom.text': 'Платите ежемесячно или экономьте с годовыми планами',
    'pricing.bottom.cta': 'Начать сегодня',

    // Facilities
    'facilities.title': 'Наши залы',
    'facilities.subtitle': 'Тренируйся как чемпион',
    'facilities.boxing': 'БОКСЕРСКИЙ РИНГ',
    'facilities.boxing.caption': 'Ринг официального соревновательного размера',
    'facilities.wrestling': 'БОРЦОВСКИЕ МАТЫ',
    'facilities.wrestling.caption': 'Высококачественные соревновательные маты',
    'facilities.conditioning': 'ЗОНА ФИЗПОДГОТОВКИ',
    'facilities.conditioning.caption': 'Современное фитнес-оборудование',
    'facilities.locker': 'РАЗДЕВАЛКИ',
    'facilities.locker.caption': 'Чистые, просторные помещения',
    'facilities.recovery': 'ЗОНА ВОССТАНОВЛЕНИЯ',
    'facilities.recovery.caption': 'Область растяжки и восстановления',
    'facilities.youth': 'ДЕТСКАЯ ТРЕНИРОВОЧНАЯ ЗОНА',
    'facilities.youth.caption': 'Безопасное пространство для юных спортсменов',

    // Testimonials
    'testimonials.title': 'Истории успеха студентов',
    'testimonials.subtitle': 'Послушайте наших чемпионов',
    'testimonials.alexander.text': 'EDESTORY превратил меня из застенчивого ребенка в уверенного молодого человека. Тренеры потрясающие и действительно заботятся о каждом студенте.',
    'testimonials.alexander.achievement': 'Региональный чемпион по боксу',
    'testimonials.alexander.program': 'Основы бокса',
    'testimonials.maria.text': 'Борьба в EDESTORY научила меня дисциплине и силе. Мне нравится поддерживающая атмосфера и сложные тренировки.',
    'testimonials.maria.achievement': 'Медалист национальной молодежи',
    'testimonials.maria.program': 'Мастерство борьбы',
    'testimonials.dmitry.text': 'Занятия фитнес-боксом для взрослых фантастические! Отличная тренировка, снятие стресса, и я изучил реальные навыки самообороны.',
    'testimonials.dmitry.achievement': 'Похудел на 15кг за 6 месяцев',
    'testimonials.dmitry.program': 'Фитнес-бокс для взрослых',
    'testimonials.elena.text': 'Детская программа такая веселая! Я научилась быть смелой и постоять за себя. Мои родители так гордятся мной.',
    'testimonials.elena.achievement': 'Чемпион младшего клуба',
    'testimonials.elena.program': 'Детские единоборства',
    'testimonials.viktor.text': 'Программа подготовки к соревнованиям интенсивная, но того стоит. Мои тренеры подтолкнули меня к достижению того, что я никогда не думал возможным.',
    'testimonials.viktor.achievement': 'Финалист национального турнира',
    'testimonials.viktor.program': 'Подготовка к соревнованиям',
    'testimonials.stats.rating': 'Средний рейтинг',
    'testimonials.stats.students': 'Довольных студентов',
    'testimonials.stats.recommend': 'Рекомендовали бы',

    // CTA Section
    'cta.title': 'Готовы начать свое путешествие?',
    'cta.subtitle': 'Присоединяйтесь к сотням студентов, которые изменили свою жизнь через боевые искусства',
    'cta.btn1': 'ЗАБРОНИРОВАТЬ ПРОБНУЮ ТРЕНИРОВКУ',
    'cta.btn2': 'ПОЗВОНИТЬ: +7 (495) 123-45-67',
    'cta.info': '🥊 Пробная тренировка включает оценку, тренировочную сессию и консультацию',
    'cta.note': 'Не требуется долгосрочных обязательств • Отмена в любое время • Приветствуются все уровни навыков',

    // Common
    'common.month': 'месяц',
    'common.session': 'занятие',
    'common.established': 'Основана',
    'common.perMonth': 'в месяц',
    'common.from': 'От',
  },
  en: {
    // Header
    'header.contact.email': 'info@edestory.com',
    'header.contact.phone': '+7 (495) 123-45-67',
    'header.follow': 'Follow Us:',
    'header.academy': 'SPORTS ACADEMY',
    'header.nav.home': 'HOME',
    'header.nav.programs': 'PROGRAMS',
    'header.nav.coaches': 'COACHES',
    'header.nav.schedule': 'SCHEDULE',
    'header.nav.shop': 'SHOP',
    'header.nav.gallery': 'GALLERY',
    'header.nav.contact': 'CONTACT',
    'header.cta': 'Free Trial',
    'header.mobile.cta': 'Start Your Free Trial',

    // Dropdown menus
    'dropdown.programs.boxing': 'Boxing Training',
    'dropdown.programs.wrestling': 'Wrestling Classes',
    'dropdown.programs.kids': 'Kids Programs (6-12)',
    'dropdown.programs.teens': 'Teen Programs (13-17)',
    'dropdown.programs.adults': 'Adult Programs (18+)',
    'dropdown.coaches.team': 'Meet Our Team',
    'dropdown.coaches.head': 'Head Coach Profile',
    'dropdown.coaches.trainers': 'Specialized Trainers',
    'dropdown.schedule.timetable': 'Class Timetable',
    'dropdown.schedule.personal': 'Personal Training',
    'dropdown.schedule.groups': 'Group Sessions',
    'dropdown.shop.boxing': 'Boxing Gear',
    'dropdown.shop.wrestling': 'Wrestling Equipment',
    'dropdown.shop.apparel': 'EDESTORY Apparel',
    'dropdown.shop.accessories': 'Training Accessories',
    'dropdown.shop.nutrition': 'Nutrition & Supplements',

    // Hero
    'hero.title1': 'FORGE YOUR',
    'hero.title2': 'WARRIOR SPIRIT',
    'hero.subtitle': 'Professional Boxing & Wrestling Training for Champions',
    'hero.description': 'Join EDESTORY Sports Academy and master the art of combat sports with world-class trainers',
    'hero.cta1': 'Start Training',
    'hero.cta2': 'Watch Video',
    'hero.slide2.title': 'BOXING MASTERY',
    'hero.slide2.subtitle': 'Master The Sweet Science',
    'hero.slide2.description': 'Develop precision, power, and technique with our championship boxing program',
    'hero.slide2.cta1': 'Join Boxing Classes',
    'hero.slide3.title': 'WRESTLING POWER',
    'hero.slide3.subtitle': 'Unleash Your Grappling Power',
    'hero.slide3.description': 'Build strength, endurance, and tactical skills with our elite wrestling program',
    'hero.slide3.cta1': 'Start Wrestling Training',
    'hero.stats.students': 'Students Trained',
    'hero.stats.champions': 'Professional Champions',
    'hero.stats.years': 'Years of Excellence',
    'hero.stats.medalists': 'Olympic Medalists on Staff',
    'hero.cards.trainers.title': 'Expert Trainers',
    'hero.cards.trainers.desc': 'World-class coaches with championship experience',
    'hero.cards.facilities.title': 'Modern Facilities',
    'hero.cards.facilities.desc': 'Professional ring, mats, and equipment',
    'hero.cards.schedule.title': 'Flexible Schedule',
    'hero.cards.schedule.desc': 'Morning, afternoon & evening classes available',
    'hero.cards.results.title': 'Proven Results',
    'hero.cards.results.desc': '95% of students achieve their fitness goals',

    // About
    'about.title': 'About EDESTORY Sports Academy',
    'about.subtitle': 'Building Champions Through Discipline & Dedication',
    'about.hero.title': 'Where Warriors Are Born',
    'about.description': 'EDESTORY Sports Academy has been the premier destination for combat sports training since 2016. Our world-class facility combines traditional martial arts wisdom with modern training methodologies.',
    'about.points.coaching': 'Expert Coaching',
    'about.points.coaching.desc': 'International championship experience',
    'about.points.results': 'Proven Results',
    'about.points.results.desc': '85% competition success rate',
    'about.points.focus': 'Individual Focus',
    'about.points.focus.desc': 'Personalized training programs',
    'about.points.development': 'Complete Development',
    'about.points.development.desc': 'Physical, mental & technical growth',
    'about.cta': 'Learn Our Story',

    // Continue with all other English translations...
    // (I'll include the key ones for brevity)
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};