import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ru' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ru: {
    // Header
    'header.contact.email': 'info@edestory.com',
    'header.contact.phone': '+7 (495) 123-45-67',
    'header.follow': 'Подписывайтесь:',
    'header.academy': 'СПОРТИВНАЯ АКАДЕМИЯ',
    'header.nav.home': 'ГЛАВНАЯ',
    'header.nav.programs': 'ПРОГРАММЫ',
    'header.nav.coaches': 'ТРЕНЕРЫ',
    'header.nav.schedule': 'РАСПИСАНИЕ',
    'header.nav.shop': 'МАГАЗИН',
    'header.nav.gallery': 'ГАЛЕРЕЯ',
    'header.nav.contact': 'КОНТАКТЫ',
    'header.cta': 'Пробная тренировка',
    'header.mobile.cta': 'Начать бесплатную тренировку',

    // Dropdown menus
    'dropdown.programs.boxing': 'Тренировки по боксу',
    'dropdown.programs.wrestling': 'Занятия борьбой',
    'dropdown.programs.kids': 'Детские программы (6-12)',
    'dropdown.programs.teens': 'Подростковые программы (13-17)',
    'dropdown.programs.adults': 'Взрослые программы (18+)',
    'dropdown.coaches.team': 'Наша команда',
    'dropdown.coaches.head': 'Главный тренер',
    'dropdown.coaches.trainers': 'Специализированные тренеры',
    'dropdown.schedule.timetable': 'Расписание занятий',
    'dropdown.schedule.personal': 'Персональные тренировки',
    'dropdown.schedule.groups': 'Групповые занятия',
    'dropdown.shop.boxing': 'Боксерское снаряжение',
    'dropdown.shop.wrestling': 'Борцовское снаряжение',
    'dropdown.shop.apparel': 'Одежда EDESTORY',
    'dropdown.shop.accessories': 'Тренировочные аксессуары',
    'dropdown.shop.nutrition': 'Питание и добавки',

    // Hero
    'hero.title1': 'СОЗДАЙ ДУХ',
    'hero.title2': 'ВОИНА',
    'hero.subtitle': 'Профессиональные тренировки по боксу и борьбе для чемпионов',
    'hero.description': 'Присоединяйся к EDESTORY Sports Academy и освой искусство боевых видов спорта с тренерами мирового класса',
    'hero.cta1': 'Начать тренировки',
    'hero.cta2': 'Смотреть видео',
    'hero.slide2.title': 'МАСТЕРСТВО БОКСА',
    'hero.slide2.subtitle': 'Освой благородное искусство',
    'hero.slide2.description': 'Развивай точность, силу и технику с нашей чемпионской программой бокса',
    'hero.slide2.cta1': 'Записаться на бокс',
    'hero.slide3.title': 'СИЛА БОРЬБЫ',
    'hero.slide3.subtitle': 'Освободи силу захватов',
    'hero.slide3.description': 'Развивай силу, выносливость и тактические навыки с нашей элитной программой борьбы',
    'hero.slide3.cta1': 'Начать борьбу',
    'hero.stats.students': 'Студентов обучено',
    'hero.stats.champions': 'Профессиональных чемпионов',
    'hero.stats.years': 'Лет совершенства',
    'hero.stats.medalists': 'Олимпийских медалистов в штате',
    'hero.cards.trainers.title': 'Опытные тренеры',
    'hero.cards.trainers.desc': 'Тренеры мирового класса с чемпионским опытом',
    'hero.cards.facilities.title': 'Современные залы',
    'hero.cards.facilities.desc': 'Профессиональный ринг, маты и оборудование',
    'hero.cards.schedule.title': 'Гибкое расписание',
    'hero.cards.schedule.desc': 'Утренние, дневные и вечерние занятия',
    'hero.cards.results.title': 'Проверенные результаты',
    'hero.cards.results.desc': '95% студентов достигают своих целей',

    // About
    'about.title': 'О СПОРТИВНОЙ АКАДЕМИИ EDESTORY',
    'about.subtitle': 'Создаем чемпионов через дисциплину и преданность',
    'about.main.title': 'Здесь рождаются воины',
    'about.main.text': 'EDESTORY Sports Academy является ведущим центром подготовки по боевым видам спорта с 2016 года. Наш современный центр сочетает традиционную мудрость боевых искусств с современными методиками тренировок.',
    'about.points.coaching': 'Экспертный коучинг',
    'about.points.coaching.desc': 'Опыт международных чемпионатов',
    'about.points.results': 'Доказанные результаты',
    'about.points.results.desc': '85% успеха в соревнованиях',
    'about.points.focus': 'Индивидуальный подход',
    'about.points.focus.desc': 'Персонализированные программы тренировок',
    'about.points.development': 'Полное развитие',
    'about.points.development.desc': 'Физический, ментальный и технический рост',
    'about.cta': 'Узнать нашу историю',

    // Programs
    'programs.title': 'ПРОГРАММЫ ТРЕНИРОВОК',
    'programs.subtitle': 'Выбери свой путь к мастерству',
    'programs.boxing.title': 'ОСНОВЫ БОКСА',
    'programs.boxing.age': 'Возраст 8-16',
    'programs.boxing.desc': 'Освой благородную науку с правильной техникой, работой ног и кондиционированием',
    'programs.boxing.price': 'От 8,000₽/месяц',
    'programs.boxing.features.1': 'Базовые техники ударов',
    'programs.boxing.features.2': 'Тренировка работы ног',
    'programs.boxing.features.3': 'Физическая подготовка',
    'programs.boxing.cta': 'Начать бокс',
    'programs.wrestling.title': 'МАСТЕРСТВО БОРЬБЫ',
    'programs.wrestling.age': 'Возраст 10-18',
    'programs.wrestling.desc': 'Развивай превосходные навыки грэпплинга, тейкдаунов и контроля на земле',
    'programs.wrestling.price': 'От 9,000₽/месяц',
    'programs.wrestling.features.1': 'Техники тейкдаунов',
    'programs.wrestling.features.2': 'Контроль на земле',
    'programs.wrestling.features.3': 'Подготовка к соревнованиям',
    'programs.wrestling.cta': 'Начать борьбу',
    'programs.kids.title': 'ДЕТСКИЕ БОЕВЫЕ ИСКУССТВА',
    'programs.kids.age': 'Возраст 6-12',
    'programs.kids.desc': 'Безопасное знакомство с боевыми искусствами с фокусом на дисциплину и веселье',
    'programs.kids.price': 'От 6,500₽/месяц',
    'programs.kids.features.1': 'Техники для возраста',
    'programs.kids.features.2': 'Развитие характера',
    'programs.kids.features.3': 'Навыки против буллинга',
    'programs.kids.cta': 'Детские классы',
    'programs.adult.title': 'ФИТНЕС-БОКС ДЛЯ ВЗРОСЛЫХ',
    'programs.adult.age': 'Возраст 18+',
    'programs.adult.desc': 'Высокоинтенсивные боксерские тренировки для фитнеса и снятия стресса',
    'programs.adult.price': 'От 7,500₽/месяц',
    'programs.adult.features.1': 'Кардио кондиционирование',
    'programs.adult.features.2': 'Техническая подготовка',
    'programs.adult.features.3': 'Управление стрессом',
    'programs.adult.cta': 'Взрослые тренировки',
    'programs.competition.title': 'ПОДГОТОВКА К СОРЕВНОВАНИЯМ',
    'programs.competition.age': 'Только для продвинутых',
    'programs.competition.desc': 'Элитные тренировки для спортсменов и подготовка к турнирам',
    'programs.competition.price': 'От 15,000₽/месяц',
    'programs.competition.features.1': 'Индивидуальный коучинг',
    'programs.competition.features.2': 'Стратегия соревнований',
    'programs.competition.features.3': 'Ментальная подготовка',
    'programs.competition.cta': 'Стать профи',
    'programs.personal.title': 'ПЕРСОНАЛЬНЫЕ ТРЕНИРОВКИ',
    'programs.personal.age': 'Все возрасты',
    'programs.personal.desc': 'Индивидуальные занятия, адаптированные под ваши конкретные цели и потребности',
    'programs.personal.price': 'От 3,500₽/занятие',
    'programs.personal.features.1': 'Индивидуальные программы',
    'programs.personal.features.2': 'Гибкое расписание',
    'programs.personal.features.3': 'Быстрый прогресс',
    'programs.personal.cta': 'Записаться',
    'programs.bottom.text': 'Не нашли подходящую программу? Свяжитесь с нами для создания индивидуального плана тренировок.',
    'programs.bottom.cta': 'Связаться с нами',

    // Why Choose Us
    'whychoose.title': 'ПОЧЕМУ ВЫБИРАЮТ EDESTORY?',
    'whychoose.subtitle': 'Что делает нас особенными',
    'whychoose.coaches.title': 'ТРЕНЕРЫ МИРОВОГО КЛАССА',
    'whychoose.coaches.stat': '15+ лет среднего опыта',
    'whychoose.coaches.desc': 'Наши тренеры - бывшие профессиональные спортсмены и сертифицированные тренеры с опытом международных соревнований.',
    'whychoose.facilities.title': 'СОВРЕМЕННЫЕ ЗАЛЫ',
    'whychoose.facilities.stat': '2,500 м² тренировочного пространства',
    'whychoose.facilities.desc': 'Профессиональный боксерский ринг, борцовские маты, современное оборудование и специальные зоны для разных типов тренировок.',
    'whychoose.methodology.title': 'ПРОВЕРЕННАЯ МЕТОДОЛОГИЯ',
    'whychoose.methodology.stat': '95% достижения целей',
    'whychoose.methodology.desc': 'Наши структурированные программы тренировок сочетают традиционные техники с современной спортивной наукой для оптимальных результатов.',
    'whychoose.programs.title': 'ГИБКИЕ ПРОГРАММЫ',
    'whychoose.programs.stat': '6 дней в неделю расписание',
    'whychoose.programs.desc': 'Утренние, дневные и вечерние занятия под ваш образ жизни. Доступны выходные мастер-классы и специальные мероприятия.',

    // Features
    'features.title': 'ЧТО ВЫ ПОЛУЧИТЕ',
    'features.subtitle': 'Полный опыт тренировок',
    'features.step1.title': 'ОЦЕНКА И ПОСТАНОВКА ЦЕЛЕЙ',
    'features.step1.desc': 'Персональная оценка и разработка индивидуального плана тренировок',
    'features.step1.time': 'Неделя 1',
    'features.step2.title': 'ОСНОВНЫЕ ТЕХНИКИ',
    'features.step2.desc': 'Освоение базовых ударов, работы ног и защитных движений',
    'features.step2.time': 'Недели 2-8',
    'features.step3.title': 'РАЗВИТИЕ НАВЫКОВ',
    'features.step3.desc': 'Продвинутые комбинации, подготовка к спаррингу и кондиционирование',
    'features.step3.time': 'Недели 9-16',
    'features.step4.title': 'ГОТОВНОСТЬ К СОРЕВНОВАНИЯМ',
    'features.step4.desc': 'Подготовка к турнирам, продвинутая стратегия и пиковая производительность',
    'features.step4.time': 'Неделя 16+',

    // Pricing
    'pricing.title': 'ТАРИФНЫЕ ПЛАНЫ',
    'pricing.subtitle': 'Гибкие варианты для каждой цели',
    'pricing.save': 'Экономьте 15% с годовым членством',
    'pricing.starter.name': 'СТАРТЕР',
    'pricing.starter.desc': 'Идеально для начинающих',
    'pricing.starter.feature1': '2 занятия в неделю',
    'pricing.starter.feature2': 'Базовое оборудование включено',
    'pricing.starter.feature3': 'Доступ к раздевалке',
    'pricing.starter.feature4': 'Программы для начинающих',
    'pricing.starter.feature5': 'Только групповые тренировки',
    'pricing.starter.cta': 'Выбрать Стартер',
    'pricing.champion.name': 'ЧЕМПИОН',
    'pricing.champion.desc': 'Самый популярный выбор',
    'pricing.champion.badge': 'ЛУЧШЕЕ ПРЕДЛОЖЕНИЕ',
    'pricing.champion.feature1': 'Безлимитные групповые занятия',
    'pricing.champion.feature2': '2 персональные тренировки',
    'pricing.champion.feature3': 'Подготовка к соревнованиям',
    'pricing.champion.feature4': 'Консультация по питанию',
    'pricing.champion.feature5': 'Доступ ко всему оборудованию',
    'pricing.champion.feature6': 'Приоритетное бронирование',
    'pricing.champion.cta': 'Выбрать Чемпион',
    'pricing.elite.name': 'ЭЛИТА',
    'pricing.elite.desc': 'Для серьезных спортсменов',
    'pricing.elite.feature1': 'Безлимитный полный доступ',
    'pricing.elite.feature2': '4 персональные тренировки',
    'pricing.elite.feature3': 'Коучинг на соревнованиях',
    'pricing.elite.feature4': 'Индивидуальные планы питания',
    'pricing.elite.feature5': 'Восстановительные процедуры',
    'pricing.elite.feature6': 'Привилегии для гостей',
    'pricing.elite.cta': 'Выбрать Элита',
    'pricing.additional.title': 'ДОПОЛНИТЕЛЬНЫЕ УСЛУГИ',
    'pricing.additional.personal': 'Персональная тренировка',
    'pricing.additional.competition': 'Подготовка к соревнованиям',
    'pricing.additional.nutrition': 'Консультация по питанию',
    'pricing.bottom.text': 'Платите ежемесячно или экономьте с годовыми планами',
    'pricing.bottom.cta': 'Начать сегодня',

    // Facilities
    'facilities.title': 'НАШИ ЗАЛЫ',
    'facilities.subtitle': 'Тренируйся как чемпион',
    'facilities.boxing.title': 'БОКСЕРСКИЙ РИНГ',
    'facilities.boxing.desc': 'Официальный ринг соревновательного размера',
    'facilities.wrestling.title': 'БОРЦОВСКИЕ МАТЫ',
    'facilities.wrestling.desc': 'Высококачественные соревновательные маты',
    'facilities.conditioning.title': 'ЗОНА КОНДИЦИОНИРОВАНИЯ',
    'facilities.conditioning.desc': 'Современное фитнес-оборудование',
    'facilities.locker.title': 'РАЗДЕВАЛКИ',
    'facilities.locker.desc': 'Чистые, просторные помещения',
    'facilities.recovery.title': 'ЗОНА ВОССТАНОВЛЕНИЯ',
    'facilities.recovery.desc': 'Зона для растяжки и восстановления',
    'facilities.youth.title': 'ДЕТСКАЯ ТРЕНИРОВОЧНАЯ ЗОНА',
    'facilities.youth.desc': 'Безопасное пространство для юных спортсменов',

    // Testimonials
    'testimonials.title': 'ИСТОРИИ УСПЕХА УЧЕНИКОВ',
    'testimonials.subtitle': 'Услышьте от наших чемпионов',
    'testimonials.alexander.text': 'EDESTORY превратила меня из застенчивого ребенка в уверенного молодого человека. Тренеры потрясающие и действительно заботятся о каждом ученике.',
    'testimonials.alexander.achievement': 'Региональный чемпион по боксу',
    'testimonials.alexander.program': 'Программа бокса для подростков',
    'testimonials.maria.text': 'Борьба в EDESTORY научила меня дисциплине и силе. Я люблю поддерживающую атмосферу и сложные тренировки.',
    'testimonials.maria.achievement': 'Медалистка национального первенства среди юниоров',
    'testimonials.maria.program': 'Женская борьба',
    'testimonials.dmitry.text': 'Занятия фитнес-боксом для взрослых фантастические! Отличная тренировка, снятие стресса, и я изучил навыки настоящей самообороны.',
    'testimonials.dmitry.achievement': 'Похудел на 15 кг за 6 месяцев',
    'testimonials.dmitry.program': 'Фитнес-бокс для взрослых',
    'testimonials.elena.text': 'Мне нравится ходить на тренировки! Тренеры очень добрые и всегда помогают. Я стала намного сильнее и увереннее.',
    'testimonials.elena.achievement': 'Победитель детского турнира',
    'testimonials.elena.program': 'Детские боевые искусства',
    'testimonials.viktor.text': 'Персональные тренировки изменили мою жизнь. Индивидуальный подход и профессиональная подготовка дали невероятные результаты.',
    'testimonials.viktor.achievement': 'Региональный чемпион среди любителей',
    'testimonials.viktor.program': 'Персональные тренировки',
    'testimonials.stats.rating': 'Средний рейтинг',
    'testimonials.stats.students': 'Довольных учеников',
    'testimonials.stats.recommend': 'Рекомендуют нас',

    // CTA Section
    'cta.title': 'ГОТОВ НАЧАТЬ СВОЙ ПУТЬ?',
    'cta.subtitle': 'Присоединяйся к сотням учеников, которые изменили свою жизнь через боевые искусства',
    'cta.stats.students': 'Учеников обучено',
    'cta.stats.success': 'Успешности',
    'cta.stats.coaches': 'Тренеров-чемпионов',
    'cta.stats.experience': 'Лет опыта',
    'cta.trial': 'ЗАПИСАТЬСЯ НА ПРОБНУЮ ТРЕНИРОВКУ',
    'cta.call': 'ПОЗВОНИТЬ: +7 (495) 123-45-67',

    // Shop
    'shop.hero.title': 'ЭКИПИРУЙСЯ КАК ЧЕМПИОН',
    'shop.hero.subtitle': 'Официальное тренировочное оборудование и одежда EDESTORY',
    'shop.hero.desc': 'Профессиональная экипировка, используемая нашими спортсменами и тренерами',
    'shop.hero.equipment': 'КУПИТЬ ЭКИПИРОВКУ',
    'shop.hero.apparel': 'ПОСМОТРЕТЬ ОДЕЖДУ',
    'shop.hero.features.shipping': 'Бесплатная доставка от 5,000₽',
    'shop.hero.features.guarantee': '30-дневная гарантия возврата денег',
    'shop.hero.features.discount': 'Скидки для студентов',
    'shop.hero.features.official': 'Официальная продукция академии',

    // Shop Categories
    'shop.categories.boxing.title': 'БОКСЕРСКОЕ ОБОРУДОВАНИЕ',
    'shop.categories.boxing.products': 'товаров',
    'shop.categories.boxing.from': 'От',
    'shop.categories.wrestling.title': 'БОРЦОВСКАЯ ЭКИПИРОВКА',
    'shop.categories.wrestling.products': 'товаров',
    'shop.categories.wrestling.from': 'От',
    'shop.categories.apparel.title': 'ТРЕНИРОВОЧНАЯ ОДЕЖДА',
    'shop.categories.apparel.products': 'товаров',
    'shop.categories.apparel.from': 'От',
    'shop.categories.fitness.title': 'ФИТНЕС АКСЕССУАРЫ',
    'shop.categories.fitness.products': 'товаров',
    'shop.categories.fitness.from': 'От',
    'shop.categories.protective.title': 'ЗАЩИТНАЯ ЭКИПИРОВКА',
    'shop.categories.protective.products': 'товаров',
    'shop.categories.protective.from': 'От',
    'shop.categories.supplements.title': 'СПОРТИВНОЕ ПИТАНИЕ',
    'shop.categories.supplements.products': 'товаров',
    'shop.categories.supplements.from': 'От',

    // Featured Products
    'shop.featured.title': 'РЕКОМЕНДУЕМЫЕ ТОВАРЫ',
    'shop.featured.subtitle': 'Отобранные нашими тренерами',

    // Common - moved to end to avoid duplicates
    'common.month': 'месяц',
    'common.session': 'занятие',
    'common.established': 'Основана'
  },
  en: {
    // Header
    'header.contact.email': 'info@edestory.com',
    'header.contact.phone': '+7 (495) 123-45-67',
    'header.follow': 'Follow Us:',
    'header.academy': 'SPORTS ACADEMY',
    'header.nav.home': 'HOME',
    'header.nav.programs': 'PROGRAMS',
    'header.nav.coaches': 'COACHES',
    'header.nav.schedule': 'SCHEDULE',
    'header.nav.shop': 'SHOP',
    'header.nav.gallery': 'GALLERY',
    'header.nav.contact': 'CONTACT',
    'header.cta': 'Free Trial',
    'header.mobile.cta': 'Start Your Free Trial',

    // Dropdown menus
    'dropdown.programs.boxing': 'Boxing Training',
    'dropdown.programs.wrestling': 'Wrestling Classes',
    'dropdown.programs.kids': 'Kids Programs (6-12)',
    'dropdown.programs.teens': 'Teen Programs (13-17)',
    'dropdown.programs.adults': 'Adult Programs (18+)',
    'dropdown.coaches.team': 'Our Team',
    'dropdown.coaches.head': 'Head Coach',
    'dropdown.coaches.trainers': 'Specialized Trainers',
    'dropdown.schedule.timetable': 'Class Schedule',
    'dropdown.schedule.personal': 'Personal Training',
    'dropdown.schedule.groups': 'Group Classes',
    'dropdown.shop.boxing': 'Boxing Equipment',
    'dropdown.shop.wrestling': 'Wrestling Gear',
    'dropdown.shop.apparel': 'EDESTORY Apparel',
    'dropdown.shop.accessories': 'Training Accessories',
    'dropdown.shop.nutrition': 'Nutrition & Supplements',

    // Hero
    'hero.title1': 'BUILD THE SPIRIT',
    'hero.title2': 'OF A WARRIOR',
    'hero.subtitle': 'Professional boxing and wrestling training for champions',
    'hero.description': 'Join EDESTORY Sports Academy and master the art of combat sports with world-class trainers',
    'hero.cta1': 'Start Training',
    'hero.cta2': 'Watch Video',
    'hero.slide2.title': 'BOXING MASTERY',
    'hero.slide2.subtitle': 'Master the Sweet Science',
    'hero.slide2.description': 'Develop precision, power, and technique with our championship boxing program',
    'hero.slide2.cta1': 'Join Boxing',
    'hero.slide3.title': 'WRESTLING POWER',
    'hero.slide3.subtitle': 'Unleash the Power of Grappling',
    'hero.slide3.description': 'Build strength, endurance, and tactical skills with our elite wrestling program',
    'hero.slide3.cta1': 'Start Wrestling',
    'hero.stats.students': 'Students Trained',
    'hero.stats.champions': 'Professional Champions',
    'hero.stats.years': 'Years of Excellence',
    'hero.stats.medalists': 'Olympic Medalists on Staff',
    'hero.cards.trainers.title': 'Expert Trainers',
    'hero.cards.trainers.desc': 'World-class coaches with championship experience',
    'hero.cards.facilities.title': 'Modern Facilities',
    'hero.cards.facilities.desc': 'Professional ring, mats, and equipment',
    'hero.cards.schedule.title': 'Flexible Schedule',
    'hero.cards.schedule.desc': 'Morning, afternoon, and evening classes',
    'hero.cards.results.title': 'Proven Results',
    'hero.cards.results.desc': '95% of students achieve their goals',

    // About
    'about.title': 'ABOUT EDESTORY SPORTS ACADEMY',
    'about.subtitle': 'Building Champions Through Discipline & Dedication',
    'about.main.title': 'Where Warriors Are Born',
    'about.main.text': 'EDESTORY Sports Academy has been the premier destination for combat sports training since 2016. Our world-class facility combines traditional martial arts wisdom with modern training methodologies.',
    'about.points.coaching': 'Expert Coaching',
    'about.points.coaching.desc': 'International championship experience',
    'about.points.results': 'Proven Results',
    'about.points.results.desc': '85% competition success rate',
    'about.points.focus': 'Individual Focus',
    'about.points.focus.desc': 'Personalized training programs',
    'about.points.development': 'Complete Development',
    'about.points.development.desc': 'Physical, mental & technical growth',
    'about.cta': 'Learn Our Story',

    // Programs
    'programs.title': 'TRAINING PROGRAMS',
    'programs.subtitle': 'Choose Your Path to Mastery',
    'programs.boxing.title': 'BOXING FUNDAMENTALS',
    'programs.boxing.age': 'Ages 8-16',
    'programs.boxing.desc': 'Master the sweet science with proper technique, footwork, and conditioning',
    'programs.boxing.price': 'From 8,000₽/month',
    'programs.boxing.features.1': 'Basic punching techniques',
    'programs.boxing.features.2': 'Footwork training',
    'programs.boxing.features.3': 'Physical conditioning',
    'programs.boxing.cta': 'Join Boxing',
    'programs.wrestling.title': 'WRESTLING MASTERY',
    'programs.wrestling.age': 'Ages 10-18',
    'programs.wrestling.desc': 'Develop superior grappling skills, takedowns, and ground control',
    'programs.wrestling.price': 'From 9,000₽/month',
    'programs.wrestling.features.1': 'Takedown techniques',
    'programs.wrestling.features.2': 'Ground control',
    'programs.wrestling.features.3': 'Competition preparation',
    'programs.wrestling.cta': 'Start Wrestling',
    'programs.kids.title': 'KIDS COMBAT SPORTS',
    'programs.kids.age': 'Ages 6-12',
    'programs.kids.desc': 'Safe introduction to martial arts focusing on discipline and fun',
    'programs.kids.price': 'From 6,500₽/month',
    'programs.kids.features.1': 'Age-appropriate techniques',
    'programs.kids.features.2': 'Character development',
    'programs.kids.features.3': 'Anti-bullying skills',
    'programs.kids.cta': 'Kids Classes',
    'programs.adult.title': 'ADULT FITNESS BOXING',
    'programs.adult.age': 'Ages 18+',
    'programs.adult.desc': 'High-intensity boxing workouts for fitness and stress relief',
    'programs.adult.price': 'From 7,500₽/month',
    'programs.adult.features.1': 'Cardio conditioning',
    'programs.adult.features.2': 'Technique training',
    'programs.adult.features.3': 'Stress management',
    'programs.adult.cta': 'Adult Training',
    'programs.competition.title': 'COMPETITION PREP',
    'programs.competition.age': 'Advanced only',
    'programs.competition.desc': 'Elite training for competitive athletes and tournament preparation',
    'programs.competition.price': 'From 15,000₽/month',
    'programs.competition.features.1': '1-on-1 coaching',
    'programs.competition.features.2': 'Competition strategy',
    'programs.competition.features.3': 'Mental preparation',
    'programs.competition.cta': 'Go Pro',
    'programs.personal.title': 'PERSONAL TRAINING',
    'programs.personal.age': 'All ages',
    'programs.personal.desc': 'One-on-one sessions tailored to your specific goals and needs',
    'programs.personal.price': 'From 3,500₽/session',
    'programs.personal.features.1': 'Customized programs',
    'programs.personal.features.2': 'Flexible scheduling',
    'programs.personal.features.3': 'Faster progress',
    'programs.personal.cta': 'Book Session',
    'programs.bottom.text': "Can't find the right program? Contact us to create a personalized training plan.",
    'programs.bottom.cta': 'Contact Us',

    // Why Choose Us
    'whychoose.title': 'WHY CHOOSE EDESTORY?',
    'whychoose.subtitle': 'What Makes Us Different',
    'whychoose.coaches.title': 'WORLD-CLASS COACHES',
    'whychoose.coaches.stat': '15+ Years Average Experience',
    'whychoose.coaches.desc': 'Our coaches are former professional athletes and certified trainers with international competition experience.',
    'whychoose.facilities.title': 'MODERN FACILITIES',
    'whychoose.facilities.stat': '2,500 m² Training Space',
    'whychoose.facilities.desc': 'Professional boxing ring, wrestling mats, modern equipment, and dedicated areas for different training types.',
    'whychoose.methodology.title': 'PROVEN METHODOLOGY',
    'whychoose.methodology.stat': '95% Goal Achievement Rate',
    'whychoose.methodology.desc': 'Our structured training programs combine traditional techniques with modern sports science for optimal results.',
    'whychoose.programs.title': 'FLEXIBLE PROGRAMS',
    'whychoose.programs.stat': '6 Days/Week Schedule',
    'whychoose.programs.desc': 'Morning, afternoon, and evening classes to fit your lifestyle. Weekend workshops and special events available.',

    // Features
    'features.title': 'WHAT YOU GET',
    'features.subtitle': 'Complete Training Experience',
    'features.step1.title': 'ASSESSMENT & GOAL SETTING',
    'features.step1.desc': 'Personal evaluation and customized training plan development',
    'features.step1.time': 'Week 1',
    'features.step2.title': 'FUNDAMENTAL TECHNIQUES',
    'features.step2.desc': 'Master basic strikes, footwork, and defensive movements',
    'features.step2.time': 'Weeks 2-8',
    'features.step3.title': 'SKILL DEVELOPMENT',
    'features.step3.desc': 'Advanced combinations, sparring preparation, and conditioning',
    'features.step3.time': 'Weeks 9-16',
    'features.step4.title': 'COMPETITION READY',
    'features.step4.desc': 'Tournament preparation, advanced strategy, and peak performance',
    'features.step4.time': 'Week 16+',

    // Pricing
    'pricing.title': 'MEMBERSHIP PLANS',
    'pricing.subtitle': 'Flexible Options for Every Goal',
    'pricing.save': 'Save 15% with Annual Membership',
    'pricing.starter.name': 'STARTER',
    'pricing.starter.desc': 'Perfect for beginners',
    'pricing.starter.feature1': '2 classes per week',
    'pricing.starter.feature2': 'Basic equipment included',
    'pricing.starter.feature3': 'Access to locker room',
    'pricing.starter.feature4': 'Beginner-friendly programs',
    'pricing.starter.feature5': 'Group training only',
    'pricing.starter.cta': 'Choose Starter',
    'pricing.champion.name': 'CHAMPION',
    'pricing.champion.desc': 'Most popular choice',
    'pricing.champion.badge': 'BEST VALUE',
    'pricing.champion.feature1': 'Unlimited group classes',
    'pricing.champion.feature2': '2 personal training sessions',
    'pricing.champion.feature3': 'Competition preparation',
    'pricing.champion.feature4': 'Nutrition consultation',
    'pricing.champion.feature5': 'Access to all equipment',
    'pricing.champion.feature6': 'Priority booking',
    'pricing.champion.cta': 'Choose Champion',
    'pricing.elite.name': 'ELITE',
    'pricing.elite.desc': 'For serious athletes',
    'pricing.elite.feature1': 'Unlimited all access',
    'pricing.elite.feature2': '4 personal training sessions',
    'pricing.elite.feature3': 'Competition coaching',
    'pricing.elite.feature4': 'Individual meal plans',
    'pricing.elite.feature5': 'Recovery treatments',
    'pricing.elite.feature6': 'Guest privileges',
    'pricing.elite.cta': 'Go Elite',
    'pricing.additional.title': 'ADDITIONAL SERVICES',
    'pricing.additional.personal': 'Personal Training Session',
    'pricing.additional.competition': 'Competition Preparation',
    'pricing.additional.nutrition': 'Nutrition Consulting',
    'pricing.bottom.text': 'Pay monthly or save with yearly plans',
    'pricing.bottom.cta': 'Start Today',

    // Facilities
    'facilities.title': 'OUR FACILITIES',
    'facilities.subtitle': 'Train Like a Champion',
    'facilities.boxing.title': 'BOXING RING',
    'facilities.boxing.desc': 'Official competition-size ring',
    'facilities.wrestling.title': 'WRESTLING MATS',
    'facilities.wrestling.desc': 'High-quality competition mats',
    'facilities.conditioning.title': 'CONDITIONING AREA',
    'facilities.conditioning.desc': 'Modern fitness equipment',
    'facilities.locker.title': 'LOCKER ROOMS',
    'facilities.locker.desc': 'Clean, spacious facilities',
    'facilities.recovery.title': 'RECOVERY ZONE',
    'facilities.recovery.desc': 'Stretching and recovery area',
    'facilities.youth.title': 'YOUTH TRAINING AREA',
    'facilities.youth.desc': 'Safe space for young athletes',

    // Testimonials
    'testimonials.title': 'STUDENT SUCCESS STORIES',
    'testimonials.subtitle': 'Hear From Our Champions',
    'testimonials.alexander.text': 'EDESTORY transformed me from a shy kid to a confident young man. The coaches are amazing and really care about each student.',
    'testimonials.alexander.achievement': 'Regional Boxing Champion',
    'testimonials.alexander.program': 'Teen Boxing Program',
    'testimonials.maria.text': 'Wrestling at EDESTORY taught me discipline and strength. I love the supportive environment and challenging training.',
    'testimonials.maria.achievement': 'National Youth Medalist',
    'testimonials.maria.program': 'Women\'s Wrestling',
    'testimonials.dmitry.text': 'Adult fitness boxing classes are fantastic! Great workout, stress relief, and I\'ve learned real self-defense skills.',
    'testimonials.dmitry.achievement': 'Lost 15kg in 6 months',
    'testimonials.dmitry.program': 'Adult Fitness Boxing',
    'testimonials.elena.text': 'I love coming to training! The coaches are very kind and always help. I became much stronger and more confident.',
    'testimonials.elena.achievement': 'Kids Tournament Winner',
    'testimonials.elena.program': 'Kids Combat Sports',
    'testimonials.viktor.text': 'Personal training changed my life. The individual approach and professional preparation gave incredible results.',
    'testimonials.viktor.achievement': 'Regional Amateur Champion',
    'testimonials.viktor.program': 'Personal Training',
    'testimonials.stats.rating': 'Average Rating',
    'testimonials.stats.students': 'Happy Students',
    'testimonials.stats.recommend': 'Recommend Us',

    // CTA Section
    'cta.title': 'READY TO START YOUR JOURNEY?',
    'cta.subtitle': 'Join hundreds of students who have transformed their lives through martial arts',
    'cta.stats.students': 'Students Trained',
    'cta.stats.success': 'Success Rate',
    'cta.stats.coaches': 'Champion Coaches',
    'cta.stats.experience': 'Years Experience',
    'cta.trial': 'BOOK FREE TRIAL',
    'cta.call': 'CALL NOW: +7 (495) 123-45-67',

    // Shop
    'shop.hero.title': 'GEAR UP LIKE A CHAMPION',
    'shop.hero.subtitle': 'Official EDESTORY Training Equipment & Apparel',
    'shop.hero.desc': 'Professional-grade gear used by our athletes and coaches',
    'shop.hero.equipment': 'SHOP EQUIPMENT',
    'shop.hero.apparel': 'VIEW APPAREL',
    'shop.hero.features.shipping': 'Free Shipping over 5,000₽',
    'shop.hero.features.guarantee': '30-Day Money Back Guarantee',
    'shop.hero.features.discount': 'Student Discounts Available',
    'shop.hero.features.official': 'Official Academy Merchandise',

    // Shop Categories
    'shop.categories.boxing.title': 'BOXING EQUIPMENT',
    'shop.categories.boxing.products': 'products',
    'shop.categories.boxing.from': 'From',
    'shop.categories.wrestling.title': 'WRESTLING GEAR',
    'shop.categories.wrestling.products': 'products',
    'shop.categories.wrestling.from': 'From',
    'shop.categories.apparel.title': 'TRAINING APPAREL',
    'shop.categories.apparel.products': 'products',
    'shop.categories.apparel.from': 'From',
    'shop.categories.fitness.title': 'FITNESS ACCESSORIES',
    'shop.categories.fitness.products': 'products',
    'shop.categories.fitness.from': 'From',
    'shop.categories.protective.title': 'PROTECTIVE GEAR',
    'shop.categories.protective.products': 'products',
    'shop.categories.protective.from': 'From',
    'shop.categories.supplements.title': 'SUPPLEMENTS',
    'shop.categories.supplements.products': 'products',
    'shop.categories.supplements.from': 'From',

    // Featured Products
    'shop.featured.title': 'FEATURED PRODUCTS',
    'shop.featured.subtitle': 'Handpicked by Our Coaches',

    // Common
    'common.month': 'month',
    'common.session': 'session',
    'common.established': 'Established'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ru']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};